
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocLPARRPARrightUNTILWEAKUNTILRELEASESTRONGRELEASEleftANDORIMPLIESEQUIVrightEVENTUALLYGLOBALLYrightNOTNEXTAND EQUIV EVENTUALLY FALSE GLOBALLY IMPLIES LPAR NEXT NOT OR RELEASE RPAR STRONGRELEASE TERM TRUE UNTIL WEAKUNTIL\n        formula : formula AND formula\n                | formula OR formula\n                | formula IMPLIES formula\n                | formula EQUIV formula\n                | formula UNTIL formula\n                | formula WEAKUNTIL formula\n                | formula RELEASE formula\n                | formula STRONGRELEASE formula\n                | NEXT formula\n                | EVENTUALLY formula\n                | GLOBALLY formula\n                | NOT formula\n                | TRUE\n                | FALSE\n                | TERM\n        \n        formula : LPAR formula RPAR\n        '
    
_lr_action_items = {'NEXT':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,]),'EVENTUALLY':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[3,3,3,3,3,3,3,3,3,3,3,3,3,3,]),'GLOBALLY':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'NOT':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[5,5,5,5,5,5,5,5,5,5,5,5,5,5,]),'TRUE':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'FALSE':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'TERM':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'LPAR':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'$end':([1,6,7,8,18,19,20,21,23,24,25,26,27,28,29,30,31,],[0,-13,-14,-15,-9,-10,-11,-12,-1,-2,-3,-4,-5,-6,-7,-8,-16,]),'AND':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[10,-13,-14,-15,-9,-10,-11,-12,10,-1,-2,-3,-4,10,10,10,10,-16,]),'OR':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[11,-13,-14,-15,-9,-10,-11,-12,11,-1,-2,-3,-4,11,11,11,11,-16,]),'IMPLIES':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[12,-13,-14,-15,-9,-10,-11,-12,12,-1,-2,-3,-4,12,12,12,12,-16,]),'EQUIV':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[13,-13,-14,-15,-9,-10,-11,-12,13,-1,-2,-3,-4,13,13,13,13,-16,]),'UNTIL':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[14,-13,-14,-15,-9,-10,-11,-12,14,-1,-2,-3,-4,14,14,14,14,-16,]),'WEAKUNTIL':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[15,-13,-14,-15,-9,-10,-11,-12,15,-1,-2,-3,-4,15,15,15,15,-16,]),'RELEASE':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[16,-13,-14,-15,-9,-10,-11,-12,16,-1,-2,-3,-4,16,16,16,16,-16,]),'STRONGRELEASE':([1,6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[17,-13,-14,-15,-9,-10,-11,-12,17,-1,-2,-3,-4,17,17,17,17,-16,]),'RPAR':([6,7,8,18,19,20,21,22,23,24,25,26,27,28,29,30,31,],[-13,-14,-15,-9,-10,-11,-12,31,-1,-2,-3,-4,-5,-6,-7,-8,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,2,3,4,5,9,10,11,12,13,14,15,16,17,],[1,18,19,20,21,22,23,24,25,26,27,28,29,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> formula AND formula','formula',3,'p_formula','ltl.py',87),
  ('formula -> formula OR formula','formula',3,'p_formula','ltl.py',88),
  ('formula -> formula IMPLIES formula','formula',3,'p_formula','ltl.py',89),
  ('formula -> formula EQUIV formula','formula',3,'p_formula','ltl.py',90),
  ('formula -> formula UNTIL formula','formula',3,'p_formula','ltl.py',91),
  ('formula -> formula WEAKUNTIL formula','formula',3,'p_formula','ltl.py',92),
  ('formula -> formula RELEASE formula','formula',3,'p_formula','ltl.py',93),
  ('formula -> formula STRONGRELEASE formula','formula',3,'p_formula','ltl.py',94),
  ('formula -> NEXT formula','formula',2,'p_formula','ltl.py',95),
  ('formula -> EVENTUALLY formula','formula',2,'p_formula','ltl.py',96),
  ('formula -> GLOBALLY formula','formula',2,'p_formula','ltl.py',97),
  ('formula -> NOT formula','formula',2,'p_formula','ltl.py',98),
  ('formula -> TRUE','formula',1,'p_formula','ltl.py',99),
  ('formula -> FALSE','formula',1,'p_formula','ltl.py',100),
  ('formula -> TERM','formula',1,'p_formula','ltl.py',101),
  ('formula -> LPAR formula RPAR','formula',3,'p_expr_group','ltl.py',122),
]
